### ISSUE TITLE
Links in the menu not taking user to the appropriate page section

### ISSUE THREAD

**Issue by forLoop94** [rmiyoyo/Portfolio-Mobile-Version-Completion#10]
1. Good job so far, @rmiyoyo, But your menu links should take the user to that section of the page.

**Comment by Bifabig** [comment]
Hi @rmiyoyo 

Great Job 👍 

I would like to suggest that you include a contributing coding partner to your readme file and also check the desktop menu hover effect to make it like the design.

**Comment by rmiyoyo** [comment]
@forLoop94 @Bifabig Thank you for raising these issues. I will close them as soon as possible.
