### ISSUE TITLE
Great Job.

### ISSUE THREAD

**Issue by CELYNEBIRUNGI** [rmiyoyo/Portfolio-Mobile-Version-Completion#19]
hi Rapheal ,
 Great Job implementing all  required the features in this project.                                                                                                                             
![unnamed](https://user-images.githubusercontent.com/113887926/233289136-10138288-f4dc-4104-b155-06b2bfeeec20.gif)
Optional suggestions

    N/A

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by peteronyam** [comment]
Great job @rmiyoyo you have got a good design but I suggest you check the portfolio buttons and make them look just as the figma design
