### ISSUE TITLE
Morning session: Peer-to-peer code review Changes ♻

### ISSUE THREAD

**Issue by abenezer-addisu** [rmiyoyo/Portfolio-Mobile-Version-Completion#20]
Hi Rapheal 🖐
I'm Abenezer your morning session partner

### **Good job so far!** 🎉

![image](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)

But there are some issues that you still need to work on  but you are almost there!

Highlights
 ✔Good job overall following the template design ✅
 ✔Correct GitHub Flow ✅

**Required Changes ♻️**

- [x] fix margin  of the about section 
- [x] make the language text inside the box 
- [x] minimize the right and left margin of the button

Your Design

![image](https://user-images.githubusercontent.com/105231513/233312019-e54867f6-7b1e-4e10-ba99-d2d23c32329d.png)

the required figma Design

![image](https://user-images.githubusercontent.com/105231513/233312671-57a83cdf-67d8-4560-a736-c1509a0e6b29.png)

Please try to mimic the figma design for a better layout.

Cheers and Happy coding!👏👏👏

**Comment by rmiyoyo** [comment]
Suggestions effected, thank you for raising them :)
