### ISSUE TITLE
peer to peer code review - pull 7

### ISSUE THREAD

**Issue by yashodhicy** [rmiyoyo/Portfolio-Mobile-Version-Completion#8]
this issue it to review the changes in pull request 7 commits

**Comment by AliShahSafdari** [comment]
1. Your commits are not descriptive 
2. You use the same sentence in two commits.

**Comment by yashodhicy** [comment]
there are 2 h1 in the HTML file. it is better to change one h1 because it can have one h1 heading in one HTML to have a good hierarchy.
